<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-QHESRBQQ" failures="3" tests="5" name="Banking App Test" time="78.778" errors="0" timestamp="2022-05-03T19:40:26 IST">
  <testcase classname="com.inetbanking.TestCases.LoginTest_002" name="loginDDT" time="23.079"/>
  <testcase classname="com.inetbanking.TestCases.LoginTest_002" name="loginDDT" time="11.326">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.LoginTest_002.loginDDT(LoginTest_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetbanking.TestCases.LoginTest_002" name="loginDDT" time="18.251"/>
  <testcase classname="com.inetbanking.TestCases.LoginTest_002" name="loginDDT" time="7.887">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.LoginTest_002.loginDDT(LoginTest_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetbanking.TestCases.LoginTest_002" name="loginDDT" time="7.613">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.LoginTest_002.loginDDT(LoginTest_002.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- Banking App Test -->
